### ISSUE TITLE
Slow jet

### ISSUE THREAD

**Issue by mattbourke** [jesion/d3js-flight-connections-map#2]
Jet doesn't go fast enough, passengers complaining.

**Comment by mattbourke** [comment]
@jesion is this jet ever going to be sped up? ;)

**Comment by Jesion** [comment]
Sure it does. Just it is a bit more complicated, because the jet's flight duration should be a function of a distance between origin and destination airports, not a simple constant.

**Comment by mattbourke** [comment]
@jesion  I'm just having a Github joke with you, I seen this appear in my feed and I thought I'd check it out, planes just seemed too slow to me.
